/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AD1.C
**     Project   : DFT_3FASES
**     Processor : MCF51QE128LQFP64
**     Beantype  : ADC
**     Version   : Bean 01.404, Driver 01.16, CPU db: 3.00.002
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 29/07/2008, 06:32 p.m.
**     Abstract  :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings  :
**         AD control register         : ADCSC1      [0xFFFF8010]
**         AD control register         : ADCCFG      [0xFFFF8016]
**         AD control register         : ADCRH       [0xFFFF8012]
**         AD control register         : ADCRL       [0xFFFF8013]
**         AD control register         : ADCCVH      [0xFFFF8014]
**         AD control register         : ADCCVL      [0xFFFF8015]
**         AD control register         : ADCSC2      [0xFFFF8011]
**         AD control register         : APCTL1      [0xFFFF8017]
**         AD control register         : APCTL2      [0xFFFF8018]
**         AD control register         : APCTL3      [0xFFFF8019]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         AD result register          : ADCres      [0xFFFF8012]
**         Interrupt name              : Vadc
**         Priority                    : 350
**         User handling procedure     : AD1_OnEnd
**         Number of conversions       : 1
**         AD resolution               : 12-bit
**
**         Input pins
**
**              Port name              : PTA
**              Bit number (in port)   : 1
**              Bit mask of the port   : 0x0002
**              Port data register     : PTAD        [0xFFFF8000]
**              Port control register  : PTADD       [0xFFFF8001]
**
**              Port name              : PTA
**              Bit number (in port)   : 6
**              Bit mask of the port   : 0x0040
**              Port data register     : PTAD        [0xFFFF8000]
**              Port control register  : PTADD       [0xFFFF8001]
**
**              Port name              : PTA
**              Bit number (in port)   : 7
**              Bit mask of the port   : 0x0080
**              Port data register     : PTAD        [0xFFFF8000]
**              Port control register  : PTADD       [0xFFFF8001]
**
**              Port name              : PTF
**              Bit number (in port)   : 6
**              Bit mask of the port   : 0x0040
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 4
**              Bit mask of the port   : 0x0010
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**              Port name              : PTF
**              Bit number (in port)   : 3
**              Bit mask of the port   : 0x0008
**              Port data register     : PTFD        [0xFFFF800A]
**              Port control register  : PTFDD       [0xFFFF800B]
**
**         Initialization:
**              Conversion             : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-2
**     Contents  :
**         Enable         - byte AD1_Enable(void);
**         Disable        - byte AD1_Disable(void);
**         EnableEvent    - byte AD1_EnableEvent(void);
**         DisableEvent   - byte AD1_DisableEvent(void);
**         Measure        - byte AD1_Measure(bool WaitForResult);
**         MeasureChan    - byte AD1_MeasureChan(bool WaitForResult, byte Channel);
**         GetValue       - byte AD1_GetValue(void* Values);
**         GetChanValue   - byte AD1_GetChanValue(byte Channel, void* Value);
**         GetValue8      - byte AD1_GetValue8(byte *Values);
**         GetChanValue8  - byte AD1_GetChanValue8(byte Channel, byte *Value);
**         GetValue16     - byte AD1_GetValue16(word *Values);
**         GetChanValue16 - byte AD1_GetChanValue16(byte Channel, word *Value);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE AD1. */

#include "Events.h"
#include "AD1.h"



static void ClrSumV(void);
/*
** ===================================================================
**     Method      :  ClrSumV (bean ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define STOP            0              /* STOP state           */
#define MEASURE         1              /* MESURE state         */
#define CONTINUOUS      2              /* CONTINUOS state      */
#define SINGLE          3              /* SINGLE state         */

static const  byte Table[6] = {0x01,0x02,0x04,0x08,0x10,0x20};  /* Table of mask constants */

static const  byte Channels[6] = {0x41,0x48,0x49,0x50,0x4E,0x4D};  /* Contents for the device control register */

static bool EnUser;                    /* Enable/Disable device */
volatile bool AD1_EnEvent;             /* Enable/Disable events */
static byte OutFlg;                    /* Measurement finish flags */
static byte SumChan;                   /* Number of measured channels */
static byte ModeFlg;                   /* Current state of device */

word AD1_OutV[6];                      /* Sum of measured values */





/*
** ===================================================================
**     Method      :  AD1_Interrupt (bean ADC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the bean.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(AD1_Interrupt)
{
  if (ModeFlg != SINGLE) {
    ((TWREG*)(&AD1_OutV[SumChan]))->b.high = ADCRH; /* Save measured value */
    ((TWREG*)(&AD1_OutV[SumChan]))->b.low = ADCRL; /* Save measured value */
    SumChan++;                         /* Number of measurement */
    if (SumChan == 6) {                /* Is number of measurement equal to the number of conversions? */
      SumChan = 0;                     /* If yes then set the number of measurement to 0 */
      OutFlg = 0x3F;                   /* Measured values are available */
      if (AD1_EnEvent) {               /* Are events enables? */
        AD1_OnEnd();                   /* If yes then invoke user event */
      }
      ModeFlg = STOP;                  /* Set the device to the stop mode */
      return;                          /* Return from interrupt */
    }
    ADCSC1 = Channels[SumChan];        /* Start measurement of next channel */
  }
  else {
    ((TWREG*)(&AD1_OutV[SumChan]))->b.high = ADCRH; /* Save measured value */
    ((TWREG*)(&AD1_OutV[SumChan]))->b.low = ADCRL; /* Save measured value */
    OutFlg |= Table[SumChan];          /* Value of measured channel is available */
    if (AD1_EnEvent) {                 /* Are events enables? */
      AD1_OnEnd();                     /* If yes then invoke user event */
    }
    ModeFlg = STOP;                    /* Set the device to the stop mode */
  }
}

/*
** ===================================================================
**     Method      :  ClrSumV (bean ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void ClrSumV(void)
{
  AD1_OutV[0] = 0;                     /* Set variable for storing measured values to 0 */
  AD1_OutV[1] = 0;                     /* Set variable for storing measured values to 0 */
  AD1_OutV[2] = 0;                     /* Set variable for storing measured values to 0 */
  AD1_OutV[3] = 0;                     /* Set variable for storing measured values to 0 */
  AD1_OutV[4] = 0;                     /* Set variable for storing measured values to 0 */
  AD1_OutV[5] = 0;                     /* Set variable for storing measured values to 0 */
}

/*
** ===================================================================
**     Method      :  AD1_HWEnDi (bean ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AD1_HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    if (ModeFlg) {                     /* Start or stop measurement? */
      if (ModeFlg != SINGLE) {
        OutFlg = 0;                    /* Output values aren't available */
        SumChan = 0;                   /* Set the number of measured channels to 0 */
        ClrSumV();                     /* Clear measured values */
      }
      else {
        OutFlg &= ~Table[SumChan];     /* Output value isn't available */
        AD1_OutV[SumChan] = 0;         /* Set variable for storing measured values to 0 */
      }
      ADCSC1 = Channels[SumChan];      /* If yes then start the conversion */
    }
  }
  else {
    ADCSC1 = 0x1F;                     /* Disable the device */
  }
}

/*
** ===================================================================
**     Method      :  AD1_Enable (bean ADC)
**
**     Description :
**         Enables A/D converter bean. <Events> may be generated
**         (<DisableEvent>/<EnableEvent>). If possible, this method
**         switches on A/D converter device, voltage reference, etc.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte AD1_Enable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    return ERR_OK;                     /* If yes then set the flag "device enabled" */
  }
  EnUser = TRUE;                       /* Set the flag "device enabled" */
  AD1_HWEnDi();                        /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_Disable (bean ADC)
**
**     Description :
**         Disables A/D converter bean. No <events> will be
**         generated. If possible, this method switches off A/D
**         converter device, voltage reference, etc.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte AD1_Disable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_OK;                     /* If yes then OK */
  }
  EnUser = FALSE;                      /* If yes then set the flag "device disabled" */
  AD1_HWEnDi();                        /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_EnableEvent (bean ADC)
**
**     Description :
**         Enables the <events>.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte AD1_EnableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  AD1_DisableEvent (bean ADC)
**
**     Description :
**         Disables the <events>.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte AD1_DisableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  AD1_Measure (bean ADC)
**
**     Description :
**         This method performs one measurement on all channels that
**         are set in the bean inspector. (Note: If the <number of
**         conversions> is more than one the conversion of A/D
**         channels is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result
**                           of a conversion. If <interrupt service>
**                           is disabled, A/D peripheral doesn't
**                           support measuring all channels at once
**                           or Autoscan mode property isn't enabled
**                           and at the same time the <number of
**                           channel> is greater than 1, then the
**                           WaitForResult parameter is ignored and
**                           the method waits for each result every
**                           time. If the <interrupt service> is
**                           disabled and a <number of conversions>
**                           is greater than 1, the parameter is
**                           ignored and the method also waits for
**                           each result every time.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already
**                           running
** ===================================================================
*/
byte AD1_Measure(bool WaitForResult)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = MEASURE;                   /* Set state of device to the measure mode */
  AD1_HWEnDi();                        /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == MEASURE) {}      /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_MeasureChan (bean ADC)
**
**     Description :
**         This method performs measurement on one channel. (Note:
**         If the <number of conversions> is more than one the
**         conversion of the A/D channel is performed specified
**         number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result
**                           of conversion. If the <interrupt service>
**                           is disabled and at the same time a
**                           <number of conversions> is greater than
**                           1, the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time.
**         Channel         - Channel number. If only one
**                           channel in the bean is set this
**                           parameter is ignored, because the
**                           parameter is set inside this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already
**                           running
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
** ===================================================================
*/
byte AD1_MeasureChan(bool WaitForResult,byte Channel)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (Channel >= 6) {                  /* Is channel number greater than or equal to 6 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = SINGLE;                    /* Set state of device to the measure mode */
  SumChan = Channel;                   /* Set required channel */
  AD1_HWEnDi();                        /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == SINGLE) {}       /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_GetValue (bean ADC)
**
**     Description :
**         Returns the last measured values for all channels. Format
**         and width of the value is a native format of the A/D
**         converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that
**                           contains the measured data. Data type is
**                           a byte, a word or an int. It depends on
**                           the supported modes, resolution, etc. of
**                           the AD converter. See the Version
**                           specific information for the current CPU
**                           in <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after the last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/
byte AD1_GetValue(void *Values)
{
  if (OutFlg != 0x3F) {                /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  ((word*)Values)[0] = AD1_OutV[0];    /* Save measured values to the output buffer */
  ((word*)Values)[1] = AD1_OutV[1];    /* Save measured values to the output buffer */
  ((word*)Values)[2] = AD1_OutV[2];    /* Save measured values to the output buffer */
  ((word*)Values)[3] = AD1_OutV[3];    /* Save measured values to the output buffer */
  ((word*)Values)[4] = AD1_OutV[4];    /* Save measured values to the output buffer */
  ((word*)Values)[5] = AD1_OutV[5];    /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_GetChanValue (bean ADC)
**
**     Description :
**         Returns the last measured value of the required channel.
**         Format and width of the value is a native format of the
**         A/D converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the bean is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value. Data
**                           type is a byte, a word or an int. It
**                           depends on the supported modes,
**                           resolution, etc. of the AD converter.
**                           See the Version specific information for
**                           the current CPU in <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after the last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/
byte AD1_GetChanValue(byte Channel,void* Value)
{
  if (Channel >= 6) {                  /* Is channel number greater than or equal to 6 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (!(OutFlg & Table[Channel])) {    /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *(word*)Value = AD1_OutV[Channel];   /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_GetValue8 (bean ADC)
**
**     Description :
**         This method returns the last measured values of all
**         channels justified to the left. Compared with <GetValue>
**         method this method returns more accurate result if the
**         <number of conversions> is greater than 1 and <AD
**         resolution> is less than 8 bits. In addition, the user
**         code dependency on <AD resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that
**                           contains the measured data.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after the last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/
byte AD1_GetValue8(byte *Values)
{
  if (OutFlg != 0x3F) {                /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  Values[0] = (byte)(AD1_OutV[0] >> 4); /* Save measured values to the output buffer */
  Values[1] = (byte)(AD1_OutV[1] >> 4); /* Save measured values to the output buffer */
  Values[2] = (byte)(AD1_OutV[2] >> 4); /* Save measured values to the output buffer */
  Values[3] = (byte)(AD1_OutV[3] >> 4); /* Save measured values to the output buffer */
  Values[4] = (byte)(AD1_OutV[4] >> 4); /* Save measured values to the output buffer */
  Values[5] = (byte)(AD1_OutV[5] >> 4); /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_GetChanValue8 (bean ADC)
**
**     Description :
**         This method returns the last measured value of required
**         channel justified to the left. Compared with
**         <GetChanValue> method this method returns more accurate
**         result if the <number of conversions> is greater than 1
**         and <AD resolution> is less than 8 bits. In addition, the
**         user code dependency on <AD resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the bean is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after the last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/
byte AD1_GetChanValue8(byte Channel,byte *Value)
{
  if (Channel >= 6) {                  /* Is channel number greater than or equal to 6 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (!(OutFlg & Table[Channel])) {    /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Value = (byte)(AD1_OutV[Channel] >> 4); /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_GetValue16 (bean ADC)
**
**     Description :
**         This method returns the last measured values of all
**         channels justified to the left. Compared with <GetValue>
**         method this method returns more accurate result if the
**         <number of conversions> is greater than 1 and <AD
**         resolution> is less than 16 bits. In addition, the user
**         code dependency on <AD resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that
**                           contains the measured data.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after the last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/
byte AD1_GetValue16(word *Values)
{
  if (OutFlg != 0x3F) {                /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  Values[0] = (word)((AD1_OutV[0]) << 4); /* Save measured values to the output buffer */
  Values[1] = (word)((AD1_OutV[1]) << 4); /* Save measured values to the output buffer */
  Values[2] = (word)((AD1_OutV[2]) << 4); /* Save measured values to the output buffer */
  Values[3] = (word)((AD1_OutV[3]) << 4); /* Save measured values to the output buffer */
  Values[4] = (word)((AD1_OutV[4]) << 4); /* Save measured values to the output buffer */
  Values[5] = (word)((AD1_OutV[5]) << 4); /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_GetChanValue16 (bean ADC)
**
**     Description :
**         This method returns the last measured value of the
**         required channel justified to the left. Compared with
**         <GetChanValue> method this method returns more accurate
**         result if the <number of conversions> is greater than 1
**         and <AD resolution> is less than 16 bits. In addition,
**         the user code dependency on <AD resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the bean is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after the last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/
byte AD1_GetChanValue16(byte Channel,word *Value)
{
  if (Channel >= 6) {                  /* Is channel number greater than or equal to 6 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (!(OutFlg & Table[Channel])) {    /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Value = (word)((AD1_OutV[Channel]) << 4); /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD1_Init (bean ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AD1_Init(void)
{
  EnUser = TRUE;                       /* Enable device */
  AD1_EnEvent = TRUE;                  /* Enable events */
  OutFlg = 0;                          /* No measured value */
  ModeFlg = STOP;                      /* Device isn't running */
  /* ADCSC2: ADACT=0,ADTRG=0,ACFE=0,ACFGT=0,??=0,??=0,??=0,??=0 */
  setReg8(ADCSC2, 0x00);               /* Disable HW trigger and autocompare */ 
  /* ADCCFG: ADLPC=0,ADIV1=0,ADIV0=1,ADLSMP=0,MODE1=0,MODE0=1,ADICLK1=0,ADICLK0=0 */
  setReg8(ADCCFG, 0x24);               /* Set prescaler bits */ 
  /* ADCSC1: COCO=0,AIEN=0,ADCO=0,ADCH4=1,ADCH3=1,ADCH2=1,ADCH1=1,ADCH0=1 */
  setReg8(ADCSC1, 0x1F);               /* Disable the module */ 
  AD1_HWEnDi();                        /* Enable/disable device according to the status flags */
}


/* END AD1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [03.89]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
