/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Parp_EDOs.C
**     Project   : DFT_3FASES
**     Processor : MCF51QE128LQFP64
**     Beantype  : TimerInt
**     Version   : Bean 02.129, Driver 01.11, CPU db: 3.00.002
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 03/08/2008, 08:05 p.m.
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : RTC (8-bit)
**         Compare name                : RTCmod
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 1024 Hz
**           Initial period/frequency
**             Xtal ticks              : 1601562
**             microseconds            : 200195
**             milliseconds            : 200
**             seconds (real)          : 0.2001953
**             Hz                      : 5
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : RTCCNT    [0xFFFF9831]
**              Mode                   : RTCSC     [0xFFFF9830]
**              Run                    : RTCSC     [0xFFFF9830]
**              Prescaler              : RTCSC     [0xFFFF9830]
**
**         Compare registers
**              Compare                : RTCMOD    [0xFFFF9832]
**
**         Flip-flop registers
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Parp_EDOs. */

#include "Events.h"
#include "PE_Error.h"
#include "Parp_EDOs.h"

/* Internal method prototypes */

/* End of Internal methods declarations */

/*
** ===================================================================
**     Method      :  Parp_EDOs_Init (bean TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Parp_EDOs_Init(void)
{
  /* RTCSC: RTIF=0,RTCLKS=0,RTIE=0,RTCPS=0 */
  setReg8(RTCSC, 0x00);                /* Stop HW */ 
  Parp_EDOs_SetCV((byte)0xCC);         /* Store appropriate value to the compare/modulo register according to High speed CPU mode */
  /* RTCSC: RTIF=1,RTCLKS=2,RTIE=1,RTCPS=2 */
  setReg8(RTCSC, 0xD2);                /* Run RTC (select clock source, set frequency and enable interrupt ) */ 
}


/*
** ===================================================================
**     Method      :  Parp_EDOs_Interrupt (bean TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Parp_EDOs_Interrupt)
{
  /* RTCSC: RTIF=1 */
  setReg8Bits(RTCSC, 0x80);            /* Reset real-time counter request flag */ 
  Parp_EDOs_OnInterrupt();             /* Invoke user event */
}



/* END Parp_EDOs. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [03.89]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
